name: Quality Checks

on:
  workflow_call:
    inputs:
      upload-coverage:
        description: "Whether to upload coverage reports"
        required: false
        type: boolean
        default: false
    secrets:
      CODECOV_TOKEN:
        description: "Codecov token for coverage upload"
        required: false

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Run linter
        run: pnpm lint

      - name: Run type check
        run: pnpm check:translations

      - name: Run tests with coverage
        run: pnpm test:coverage

      - name: Upload coverage to Codecov
        if: inputs.upload-coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
